[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
script = 'ignored_scripts'
cache_path  = 'cache_forge'
via_ir = true
ignored_error_codes = [3628, 2072, 5667, 2018]
optimizer = true
optimizer_runs = 200
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts-ccip/contracts/=node_modules/@chainlink/contracts-ccip/contracts/",
    "@chainlink/contracts/=node_modules/@chainlink/contracts/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/"
]